# Generated by Django 3.1.6 on 2021-02-23 21:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=product.models.document_images_file_path)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('composition', models.TextField()),
                ('quantity', models.IntegerField(default=0)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='manufacturers.manufacturermodel')),
            ],
        ),
    ]
