# Generated by Django 3.1.6 on 2021-02-23 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('total_products', models.IntegerField(default=0)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
