# Generated by Django 3.1.6 on 2021-02-23 21:12

from django.db import migrations, models
import manufacturers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=manufacturers.models.document_images_file_path)),
            ],
        ),
    ]
