# Generated by Django 3.1.6 on 2021-07-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturer/'),
        ),
    ]
