# Generated by Django 3.1.6 on 2021-07-31 17:21

from django.db import migrations, models
import manufacturers.models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_auto_20210731_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=manufacturers.models.document_images_file_path),
        ),
    ]
