# Generated by Django 3.1.6 on 2021-08-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0003_auto_20210731_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturermodel',
            options={'ordering': ('priority',)},
        ),
    ]
