# Generated by Django 3.1.6 on 2021-03-03 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_set', related_query_name='items', to='cart.CartItem'),
        ),
    ]
