# Generated by Django 3.1.6 on 2021-03-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210303_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.cartmodel'),
            preserve_default=False,
        ),
    ]
