# Generated by Django 3.1.6 on 2021-03-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_address_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_checkedout',
            field=models.BooleanField(default=False),
        ),
    ]
