# Generated by Django 3.1.6 on 2021-03-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_is_checkedout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='items',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartitem'),
            preserve_default=False,
        ),
    ]
