# Generated by Django 3.1.6 on 2021-03-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210304_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='items',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='cart_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cartitem'),
        ),
    ]
