# Generated by Django 3.1.6 on 2021-03-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20210304_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='status',
        ),
    ]
