# Generated by Django 3.1.6 on 2021-02-04 09:52

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('discover', models.CharField(max_length=255)),
                ('practice_license', models.ImageField(null=True, upload_to=user.models.document_images_file_path)),
                ('premise_license', models.ImageField(null=True, upload_to=user.models.document_images_file_path)),
            ],
        ),
    ]
