# Generated by Django 3.1.6 on 2021-02-05 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210204_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='user',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
