# Generated by Django 3.1.6 on 2021-02-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210205_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='created',
        ),
    ]
