# Generated by Django 3.1.6 on 2021-02-05 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_phoneotp_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
