# Generated by Django 3.1.6 on 2021-02-05 04:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_phoneotp_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
