# Generated by Django 3.1.6 on 2021-02-05 13:16

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210205_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='discover',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='practice_license',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.document_images_file_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='premise_license',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.document_images_file_path),
        ),
    ]
