# Generated by Django 3.1.6 on 2021-03-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210205_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erp_id',
            field=models.IntegerField(default=0),
        ),
    ]
