# Generated by Django 3.1.6 on 2021-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210315_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='erp_access',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='erp_id_2',
            field=models.IntegerField(default=0),
        ),
    ]
