# Generated by Django 3.1.6 on 2021-08-02 14:05

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210607_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discover',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_license',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.document_images_file_path),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_license_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='premise_license',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.document_images_file_path),
        ),
        migrations.AddField(
            model_name='user',
            name='premise_license_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
