# Generated by Django 3.1.6 on 2021-08-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210802_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discover',
            field=models.CharField(choices=[('linkedin', 'Linkedin'), ('instagram', 'Instagram'), ('acquisition-team', 'Acquisition Team'), ('facebook', 'Facebook'), ('google-search', 'Google Search'), ('sales-rep', 'Sales Rep'), ('referral', 'Referral'), ('others', 'Others')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('lagos', 'Lagos State'), ('ogun', 'Ogun State'), ('oyo', 'Oyo State'), ('abuja', 'Abuja (FCT) State'), ('rivers', 'Rivers State'), ('abia', 'Abia State'), ('adamawa', 'Adamawa State'), ('akwa-ibon', 'Akwa Ibon State'), ('bauchi', 'Bauchi State'), ('bayelsa', 'Bayelsa State'), ('benue', 'Benue State'), ('borno', 'Borno State'), ('cross-rivers', 'Cross Rivers State'), ('deltaz', 'Delta State'), ('ebonyi', 'Ebonyi State'), ('edo', 'Edo State'), ('ekitiz', 'Ekiti State'), ('enugu', 'Enugu State'), ('gombe', 'Gombe State'), ('imo', 'Imo State'), ('jigawa', 'Jigawa State'), ('kaduna', 'Kaduna State'), ('kano', 'Kano State'), ('katsina', 'Katsina State'), ('kebbi', 'Kebbi State'), ('kogi', 'Kogi State'), ('kwara', 'Kwara State'), ('nasarawa', 'Nasarawa State'), ('niger', 'Niger State'), ('ondo', 'Ondo State'), ('plateau', 'Sokoto State'), ('sokoto', 'Plateau State'), ('taraba', 'Taraba State'), ('yobe', 'Yobe State'), ('zamfara', 'Zamfara State')], max_length=255, null=True),
        ),
    ]
